included:
  - Sources
  - Tests
excluded:
  - Tests/MVDSTests/stubs
  - Tests/MVDSTests/XCTestManifests.swift
file_name:
  excluded:
    - Package.swift
    - LinuxMain.swift
identifier_name:
  excluded:
    - id
    - to
